version: 2.1
orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test-py-311-django-4-1:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pip install tox && tox -e py311-django4.1
workflows:
  sample:
    jobs:
      - build-and-test-py-311-django-4-1
